services:

  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

  # Create a topic called purchases
  kafka-init:
    image: 'bitnami/kafka:latest'
    command: 'kafka-topics.sh --create --topic purchases --partitions 1 --replication-factor 1 --bootstrap-server kafka:9092'
    depends_on:
      - kafka
    init: true

  kafka-ui:
    image: 'provectuslabs/kafka-ui:latest'
    restart: always
    depends_on:
      - kafka
    ports:
      - '8080:8080'
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092

  producer-consumer:
    image: kafka-producer-consumer
    depends_on:
      - kafka-init
    build:
      context: .
      dockerfile: Dockerfile